alias cat 'bat'
alias ping 'prettyping --nolegend'
alias top 'htop'
alias du 'ncdu --color dark -rr -x'
alias ls 'eza --group-directories-first --classify --icons --hyperlink'
alias l 'ls'
alias la 'eza --group-directories-first --classify --icons -a --hyperlink'
alias ll 'eza --group-directories-first --classify --icons -l --hyperlink'
alias rm 'rm -I'
alias bkup 'btrbk -c .config/btrbk.conf -v --pretty --progress run'

# go up directories easier
alias .. 'cd ..'
alias ... 'cd ../..'
alias .... 'cd ../../..'
alias ..... 'cd ../../../..'
